name: contexts
on: push
jobs:
  functions: 
    runs-on: ubuntu-latest
    steps:
      - name: contains
        run: 
          eccho ${{contains('Hello world', 'llo')}}
      - name: startsWith
        if: failure()
        run: 
          echo ${{startsWith('Hello world', 'He')}}
          echo ${{endsWith('Hello world', 'He')}}
          echo ${{format('Hello {0} {1} {2}', 'Mona', 'the', 'Octocat')}}

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'