name: matrix

on: push

jobs:
  node-setup: 
    runs-on: ubuntu-latest
    steps:
      - name: node-setup
        run: node -v
      - uses: actions/setup-node@v1
        with:
         node-version: 6
      - name: node-setup
        run: node -v