name: matrix

on: push

jobs:
  node-setup: 
    strategy:
      matrix: 
        node-version: [6,8,10]
      #max-parallel: 0 #we can limit the parallel occurence of jobs(default=0)
      #fail-fast: false # 6,8,10 will run independently 
      #fail-fast: true # every thing will stop if one of 6,8,10 fails. 
    runs-on: ubuntu-latest
    steps:
      - name: node-setup
        run: node -v
      - uses: actions/setup-node@v1
        with:
         node-version: 6
      - name: node-setup
        run: node -v