name: matrix

on: push

jobs:
  node-setup: 
    strategy:
      matrix: 
        os: [macos-latest,ubuntu-latest] # run 6 times
        node-version: [6,8,10]
        include: #adds this set 
          - os: ubuntu-latest
            node-version: 5
        exclude: #excludes or ignores this set
          - os: ubuntu-latest
            node-version: 6

      #max-parallel: 0 #we can limit the parallel occurence of jobs(default=0)
      #fail-fast: false # 6,8,10 will run independently 
      #fail-fast: true # every thing will stop if one of 6,8,10 fails. 
    runs-on: ${{matrix.os}}
    steps:
      - name: node-setup
        run: node -v
      - uses: actions/setup-node@v1
        with:
         #node-version: 6 #takes only 6 every time.
         node-version: ${{matrix.node-version}} #will take iterative versions.
      - name: node-setup
        run: node -v