name: shell commands

on: [push]

jobs:
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: eccho a string 
        run: eccho "HEllo world"
      - name: multiline script
        run: |
          node -v
          npm -v
