name: shell commands

on: [push]

jobs:
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: echo a string 
        run: echo "HEllo world"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run : |
          print(2+3)
          import Math as m
          print(m.sqrt(4))
        shell: python
